name: 'Slack Webhook'
description: 'Notify slack'
inputs:
  slack_webhook_url:
    description: 'slack_webhook_url'
    required: true
runs:
  using: "composite"
  steps:
    # - name: Get workflow status
    #   uses: technote-space/workflow-conclusion-action@v3

    # Start a Slack workflow using a webhook trigger
    # https://github.com/slackapi/slack-github-action

    - name: Send initial Slack message
      id: slack_notify
      uses: slackapi/slack-github-action@v2.1.0
      with:
        payload: |
          {
            "text": ":rocket: Terraformチェックが開始されました。",
            "unfurl_links": false
          }
        webhook: ${{ inputs.slack_webhook_url }}
        webhook-type: incoming-webhook

    - name: Send GitHub Action trigger data to Slack workflow
      uses: slackapi/slack-github-action@v2.1.0
      # env:
      #     STATUS_ICON: ${{ job.status == 'success' && ':white_check_mark:' || ':x:' }}
      #     STATUS_TEXT: ${{ job.status == 'success' && '成功' || '失敗' }}
      #     DEPLOY_STATUS: ${{ job.status == 'success' && 'CDKデプロイが完了しました！' || 'CDKデプロイに失敗しました。' }}
      #     COMMIT_URL: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
      with:
        webhook: ${{ inputs.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload: |
            {
              "thread_ts": "${{ steps.slack_notify.outputs.ts }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "ビルド結果: test"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Author: test"
                    }
                  ]
                }
              ]
            }
