name: Notify Slack with Thread per PR

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["CI"]  # 任意のWorkflow名
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ↓ Gistから thread_ts を読み込む
      - name: Try to get thread_ts from Gist
        id: download
        continue-on-error: true
        run: |
          gist_id="${{ secrets.SLACK_THREADS_GIST_ID }}"
          filename="pr-${{ github.event.pull_request.number }}.txt"
          
          response=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/gists/$gist_id")
          
          thread_ts=$(echo "$response" | jq -r --arg filename "$filename" \
            '.files[$filename].content // empty')
          
          if [[ -n "$thread_ts" ]]; then
            echo "$thread_ts" > thread_ts.txt
            echo "download-path=." >> "$GITHUB_OUTPUT"
          fi

      - name: Read thread_ts if exists
        id: read_thread
        if: steps.download.outputs.download-path != ''
        run: |
          if [[ -f "thread_ts.txt" ]]; then
            thread_ts=$(cat thread_ts.txt)
            echo "thread_ts=$thread_ts" >> "$GITHUB_OUTPUT"
            echo "Read thread_ts from file: $thread_ts"
          fi

      # ↓ thread_ts が存在しなければ新しくSlackに投稿（親メッセージ）
      - name: Post to Slack (initial or fallback)
        id: deployment_message
        if: steps.read_thread.outputs.thread_ts == ''
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": ":sparkles: PR #${{ github.event.pull_request.number }} が更新されました！"
            }

      # ↓ thread_ts を保存（初回 or fallback のみ）
      - name: Save thread_ts to file
        if: steps.read_thread.outputs.thread_ts == ''
        run: |
          echo "${{ steps.deployment_message.outputs.ts }}" > thread_ts.txt

      - name: Upload thread_ts to Gist
        if: steps.read_thread.outputs.thread_ts == ''
        run: |
          gist_id="${{ secrets.SLACK_THREADS_GIST_ID }}"
          filename="pr-${{ github.event.pull_request.number }}.txt"
          thread_ts="${{ steps.deployment_message.outputs.ts }}"
          
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/gists/$gist_id" \
            -d "{
              \"files\": {
                \"$filename\": {
                  \"content\": \"$thread_ts\"
                }
              }
            }"

      # ↓ スレッドに返信
      - name: Post Slack thread reply
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "thread_ts": "${{ steps.read_thread.outputs.thread_ts || steps.deployment_message.outputs.ts }}",
              "text": ":white_check_mark: GitHub Actions が実行されました（成功 or 失敗）"
            }
