name: Notify Slack with Thread per PR (via PAT)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Gist から thread_ts を取得
      - name: Get thread_ts from Gist
        id: read_thread
        run: |
          gist_id="${{ secrets.SLACK_THREADS_GIST_ID }}"
          filename="pr-${{ github.event.pull_request.number }}.txt"

          response=$(curl -s \
            -H "Authorization: token ${{ secrets.TERRAFORM_GITHUB_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/gists/$gist_id")

          thread_ts=$(echo "$response" | jq -r --arg filename "$filename" \
            '.files[$filename].content // empty')

          if [[ -n "$thread_ts" ]]; then
            echo "thread_ts=$thread_ts" >> "$GITHUB_OUTPUT"
            echo "Found existing thread_ts: $thread_ts"
          else
            echo "thread_ts=" >> "$GITHUB_OUTPUT"
          fi

      # 2. thread_ts がない場合は Slack に新規投稿
      - name: Post to Slack (initial message)
        id: slack_post
        if: steps.read_thread.outputs.thread_ts == ''
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": ":sparkles: PR #${{ github.event.pull_request.number }} が更新されました！"
            }

      # 3. thread_ts を Gist に保存(新規メッセージのみ)
      - name: Save thread_ts to Gist
        if: steps.read_thread.outputs.thread_ts == ''
        run: |
          gist_id="${{ secrets.SLACK_THREADS_GIST_ID }}"
          filename="pr-${{ github.event.pull_request.number }}.txt"
          thread_ts="${{ steps.slack_post.outputs.ts }}"

          echo "Saving thread_ts to Gist..."
          curl -v -X PATCH \
            -H "Authorization: token ${{ secrets.TERRAFORM_GITHUB_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/gists/$gist_id" \
            -d "{
              \"files\": {
                \"$filename\": {
                  \"content\": \"$thread_ts\"
                }
              }
            }"

      # 4. スレッドに返信
      - name: Post to Slack thread
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "thread_ts": "${{ steps.read_thread.outputs.thread_ts || steps.slack_post.outputs.ts }}",
              "text": ":white_check_mark: GitHub Actions が実行されました（成功 or 失敗）"
            }
