name: Notify Slack with Thread per PR

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. GitHub App Token を取得
      - name: Create GitHub App token
        if: github.event_name == 'pull_request'
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TERRAFORM_GITHUB_APP_ID }}
          private-key: ${{ secrets.TERRAFORM_GITHUB_PRIVATE_KEY }}

      # 2. PR コメントから thread_ts を取得
      - name: Get thread_ts from PR comments
        if: github.event_name == 'pull_request'
        id: read_thread
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          repo="${{ github.repository }}"

          echo "Fetching thread_ts from PR #$pr_number comments..."

          thread_ts=$(gh pr view "$pr_number" --repo "$repo" --json comments 2>/dev/null \
            | jq -r '.comments[]?.body // empty' 2>/dev/null \
            | grep -oE '<!-- slack_thread_ts: [0-9]+\.[0-9]+ -->' 2>/dev/null \
            | tail -n1 \
            | grep -oE '[0-9]+\.[0-9]+' 2>/dev/null || true)

          if [[ -n "$thread_ts" ]]; then
            echo "thread_ts=$thread_ts" >> "$GITHUB_OUTPUT"
            echo "Found existing thread_ts: $thread_ts"
          else
            echo "thread_ts=" >> "$GITHUB_OUTPUT"
            echo "No thread_ts found"
          fi

      # 3. thread_ts がない場合は Slack に新規投稿
      - name: Post to Slack (initial message)
        if: github.event_name == 'pull_request' && steps.read_thread.outputs.thread_ts == ''
        id: slack_post
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              channel: ${{ secrets.SLACK_CHANNEL_ID }},
              text: "Pull request <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}> ${{ github.event.action == 'opened' && 'opened' || github.event.action == 'reopened' && 'reopened' || 'modified' }}\n\n
                    Opened by <${{ github.event.pull_request.user.html_url }}|${{ github.event.pull_request.user.login }}>\n
                    <${{ github.server_url }}/${{ github.repository }}/actions|Actions link>",
              unfurl_links: false,
              unfurl_media: false
            }

      # 4. thread_ts を PR にコメント(新規メッセージのみ)
      - name: Save thread_ts to PR comment
        if: github.event_name == 'pull_request' && steps.read_thread.outputs.thread_ts == ''
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          repo="${{ github.repository }}"
          thread_ts="${{ steps.slack_post.outputs.ts }}"

          echo "Saving thread_ts to PR comment..."
          gh pr comment "$pr_number" \
            --repo "$repo" \
            --body "<!-- slack_thread_ts: $thread_ts -->"

      # 5. スレッドに投稿
      - name: Post to Slack thread
        if: github.event_name == 'pull_request'
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              channel: ${{ secrets.SLACK_CHANNEL_ID }},
              thread_ts: ${{ steps.read_thread.outputs.thread_ts || steps.slack_post.outputs.ts }},
              text: "Pull request <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}> ${{ github.event.action == 'opened' && 'opened' || github.event.action == 'reopened' && 'reopened' || 'modified' }}\n\n
                    Opened by <${{ github.event.pull_request.user.html_url }}|${{ github.event.pull_request.user.login }}>\n
                    <${{ github.server_url }}/${{ github.repository }}/actions|Actions link>",
              unfurl_links: false,
              unfurl_media: false
            }

      # Slack にコメントを転送
      - name: Send comment to Slack thread
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request && steps.read_thread.outputs.thread_ts != ''
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "thread_ts": "${{ steps.read_thread.outputs.thread_ts }}",
              "text": "*New comment on PR <${{ github.event.issue.html_url }}|#${{ github.event.issue.number }}> by <${{ github.event.comment.user.html_url }}|${{ github.event.comment.user.login }}>*:\n\n${{ github.event.comment.body }}"
            }
